require "user.main"
require "user.pckr"
require "user.keymaps"
require "user.telescope"
require "user.themery"
require 'user.treesitter'
require 'user.lualine'
require 'user.lsp.init'
require 'user.neoscroll'
